In [4]:
# set runtime to T4 GPU
from transformers import pipeline

# Load the fine-tuned BERT-Emotion model
sentiment_analysis = pipeline("text-classification", model="boltuix/bert-emotion")

# Analyze emotion
result = sentiment_analysis("i love you")
print(result)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.20k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/44.7M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/262k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Device set to use cuda:0

[{'label': 'love', 'score': 0.8442273736000061}]

In [5]:
sentiment_analysis(["this product does not work well", "i like that product"])

[{'label': 'disgust', 'score': 0.4893624484539032},
 {'label': 'love', 'score': 0.7557116746902466}]

In [6]:
import pandas as pd

In [2]:
df = pd.read_csv("https://github.com/christianw/applied-ux/raw/main/week03/amazon_reviews.csv.xz", low_memory=False)

In [3]:
pos_mask = df["name"] == "Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta"

In [7]:
pos = df[pos_mask].copy()

In [8]:
len(pos)

10966

In [9]:
pos.dtypes

id                       object
name                     object
asins                    object
brand                    object
categories               object
keys                     object
manufacturer             object
reviews.date             object
reviews.dateAdded        object
reviews.dateSeen         object
reviews.didPurchase      object
reviews.doRecommend      object
reviews.id              float64
reviews.numHelpful      float64
reviews.rating          float64
reviews.sourceURLs       object
reviews.text             object
reviews.title            object
reviews.userCity        float64
reviews.userProvince    float64
reviews.username         object
dtype: object

In [10]:
sentiments = sentiment_analysis(list(pos["reviews.title"].map(str)))

In [11]:
pos["sentiment"] = [s["label"] for s in sentiments]

In [ ]:
pos["reviews.title"].map(str).values[0:10]

array(['Great product', 'Great product', 'Great product and service',
       'very good product and service.', 'Good selection.',
       'Exactly what I wanted', 'Good but not great', 'OK',
       'Great kindle.', 'Too small'], dtype=object)

In [12]:
pos["sentiment"].value_counts()

sentiment
love         7433
neutral      1770
happiness    1274
anger         148
disgust       126
fear          106
sadness        66
confusion      23
surprise       13
desire          5
shame           1
guilt           1
Name: count, dtype: int64

In [ ]:
# now you could look for quotes etc.